from tkinter.font import names

import yaml
import json
import logging
from opik import track
from opik.integrations.genai import track_genai
from app.services.agent import Agent, SuperAgent
from app.settings import get_settings
from app.services.recipe import PdfInformationRecipe
from app.services.tools.agent_tools import UrlFetchFirebaseDBPythonExamplesTool

settings = get_settings()
logger = logging.getLogger(__name__)


class ChatbotService:
    def __init__(self):

        self.agent = None

    def load_prompt_from_file(self, file_path: str):
        """
        Load the prompt from a YAML file.

        :param file_path: Path to the YAML file containing the prompt.
        :return: Loaded prompt as a dictionary.
        """
        try:
            with open(file_path, 'r') as file:
                prompt = yaml.safe_load(file)
            return prompt
        except Exception as e:
            raise ValueError(f"Error loading prompt from file: {e}")

    def load_agents(self, db_schema: PdfInformationRecipe = None):

        db_prompt = self.load_prompt_from_file(settings.DB_AGENT_PROMPT_FILE_PATH)
        try:
            if "firestore_db_schema"  in db_prompt:
                db_prompt["firestore_db_schema"] = json.dumps(db_schema.model_json_schema())
        except Exception as e:
            logger.info(f"Error loading firestore db schema: {e}")
        self.db_agent = Agent(
            name="db_agent",
            description="An agent to interact with the google cloud firebase database and retrieve information.",
            model_name=settings.DB_AGENT_MODEL,  # Replace with actual model name
            prompt=db_prompt,  # Load prompt from file
            tools={
                "fetch_firebase_db_python_examples": UrlFetchFirebaseDBPythonExamplesTool()
            }  # Define tools if needed
        )
        self.information_validation_agent = Agent(
            name="information_and_response_validation_agent",
            description="An agent to validate if information is correct and to validate the response generated by the chatbot.",
            model_name=settings.INFORMATION_VALIDATION_AGENT_MODEL,
            prompt=self.load_prompt_from_file(settings.INFORMATION_VALIDATION_AGENT_PROMPT_FILE_PATH),
        )
        self.super_agent = SuperAgent(
            name = "Super Agent",
            description = "A super agent that orchestrates the database agent and information validation agent.",
            model_name = settings.SUPER_AGENT_MODEL,
            prompt=self.load_prompt_from_file(settings.SUPER_AGENT_PROMPT_FILE_PATH),
            agents = {
                "db_agent": self.db_agent,
                "information_and_response_validation_agent": self.information_validation_agent
            }
        )


    @track("chatbot_service.get_response")
    def get_response(self, query: str, db_service=None):
        """
        Get a response from the chatbot for a given message.
        """
        if not query:
            raise ValueError("Query cannot be empty.")

        self.load_agents(PdfInformationRecipe)

        response = self.super_agent.execute(query)

        if not response:
            raise ValueError("No response generated by the chatbot.")

        return response