import yaml
from opik import track

from app.services.agent import Agent
from app.settings import get_settings
from app.services.recipe import PdfInformationRecipe

settings = get_settings()

class ChatbotService:
    def __init__(self):

        self.agent = None
        self.load_agents()

    def load_prompt_from_file(self, file_path: str):
        """
        Load the prompt from a YAML file.

        :param file_path: Path to the YAML file containing the prompt.
        :return: Loaded prompt as a dictionary.
        """
        try:
            with open(file_path, 'r') as file:
                prompt = yaml.safe_load(file)
            return prompt
        except Exception as e:
            raise ValueError(f"Error loading prompt from file: {e}")

    def load_agents(self, db_schema: PdfInformationRecipe = None):

        prompt = self.load_prompt_from_file(settings.DB_AGENT_PROMPT_FILE_PATH)
        try:
        if "firestore_db_schema"  in prompt:
            prompt["firestore_db_schema"] = db_schema.model_json_schema()




        self.db_agent = Agent(
            name="Database Agent",
            description="An agent to interact with the google cloud firebase database and retrieve information.",
            model_name=settings.DB_AGENT_MODEL,  # Replace with actual model name
            prompt=,  # Load prompt from file
            tools=[]  # Define tools if needed
        )


    @track("chatbot_service.get_response")
    def get_response(self, query: str, db_service=None):
        """
        Get a response from the chatbot for a given message.
        """
        if not query:
            raise ValueError("Query cannot be empty.")

        if db_service is None:
            raise ValueError("Database service is required to get a response.")

        # Get the response from the chatbot
        response = self.db_agent.execute(query)

        if not response:
            raise ValueError("No response generated by the chatbot.")

        return response